info:
  app:
    name: AdventureBooks
    version: 0.0.4
    description: Implement an adventure book REST API
server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  application:
    name: adventure
  sql:
    init:
      mode: always
      platform:
        postgres
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: dev