info:
  app:
    name: AdventureBooks
    version: 0.0.4
    description: Implement an adventure book REST API
server:
  port: ${SERVER_PORT:8081}

#logging:
#  level:
#    root: DEBUG

spring:
  application:
    name: adventure
  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/adventure}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:adventure}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
